"""Language gate for the Ilai Collective content engine.

scan(text) -> list of (category, match) tuples. Empty list means clean.

This is the AI-slop layer of the Dr. Leaf / Ilai master language rules
(vault: dr-leaf-master-language-rules.md), retuned for a human-led creative
agency. It deliberately DROPS the Dr. Leaf domain bans (calm, system, hold,
pause, nervous-system, mind-brain doctrine) because those are legitimate
words in agency copy. It keeps the transferable hard-fail layer: AI lexicon,
AI phrases, contrast cadence, em-dash, weasel adverbs, hype, platitudes,
throat-clearing, LLM leaks, plus the two Ilai compliance rules.

The banned list is a SLOP filter, not a vocabulary cage. Keep it small on
purpose; over-banning is itself a tell.
"""
import re

# 8a. AI_LEXICON — never-legitimate AI puffery (HARD)
AI_LEXICON = [
    "delve", "delves", "delved", "delving", "tapestry", "tapestries",
    "testament", "underscore", "underscores", "underscored", "underscoring",
    "boast", "boasts", "boasting", "boasted", "vibrant", "captivating",
    "majestic", "nestled", "seamless", "seamlessly", "showcase", "showcases",
    "showcased", "showcasing", "myriad", "plethora",
]

# 8b. AI_PHRASES — scaffolding + promotional puffery (HARD)
AI_PHRASE = [
    "stands as a testament", "a testament to", "rich tapestry",
    "it's worth noting", "it is worth noting", "worth noting",
    "in conclusion", "in summary", "to summarize", "a myriad of",
    "treasure trove", "in today's fast-paced world", "in today's digital age",
    "fast-paced world", "in the realm of", "navigating the complexities",
    "navigate the complexities", "serves as a reminder", "a powerful reminder",
    "plays a pivotal role", "plays a crucial role", "plays a vital role",
    "it's important to note", "it is important to note", "important to note",
    "in a world where", "the future is bright", "the future looks bright",
]

# Hype / marketing puffery + the "extraordinary" cluster (HARD).
HYPE = [
    "transformative", "transformational", "groundbreaking", "game-changing",
    "game changing", "revolutionary", "revolutionize", "supercharge",
    "supercharged", "unlock", "unlocking", "unlocked", "unleash", "unleashed",
    "unleashing", "extraordinary", "staggering", "stunning", "breathtaking",
    "jaw-dropping", "jaw dropping", "cutting-edge", "world-class",
    "best-in-class", "10x", "skyrocket", "effortless", "effortlessly",
]

# Weasel adverbs / empty intensifiers (HARD — from the master banned list).
WEASEL = [
    "quietly", "secretly", "subtly", "genuinely", "remarkable", "remarkably",
    "profound", "profoundly", "incredible", "incredibly", "low-key", "low key",
]

# Throat-clearing (delete on sight).
THROAT = [
    "bottom line", "at the end of the day", "here's the thing",
    "heres the thing", "the truth is", "let's face it", "let's be honest",
    "needless to say", "that being said",
]

# Platitude / Barnum phrases (HARD).
PLATITUDE = [
    "trust the process", "your journey", "do the work", "show up for yourself",
    "living your best life", "you've got this", "at your fingertips",
    "the sky's the limit", "take it to the next level",
]

# LLM leftover assistant chatter (HARD, substring — matches the master LLM_LEAK).
LLM_LEAK = [
    "as an ai language model", "as a language model", "as an ai model",
    "as an ai", "i'm an ai", "i am an ai", "i hope this helps",
    "hope this helps", "i cannot fulfill", "let me know if you'd like",
    "feel free to let me know", "certainly! here", "sure here's",
    "of course! here", "here's a draft", "here is a draft", "[insert",
    "[your name", "[topic]", "fill in the blank",
]

# COMPLIANCE — Ilai hard brand rules. Never appear.
COMPLIANCE = [
    "we use ai", "we use artificial intelligence", "ai-generated",
    "ai generated", "generated by ai", "written by ai", "we scrape",
    "scraping", "scraped", "our ai", "using ai to", "powered by ai",
    "ai writes", "ai-written",
]

# 9b. Contrast / reframe cadence — the #1 AI tell (HARD).
CONTRAST_PATTERNS = [
    re.compile(r"\bnot only\b[^.?!]*\bbut also\b", re.I),
    re.compile(r"\bit['’]s not just\b[^.?!]*,?\s*it['’]s\b", re.I),
    re.compile(r"\bit['’]s not about\b[^.?!]*\bit['’]s about\b", re.I),
    re.compile(r"\bthis isn['’]t about\b[^.?!]*\bthis is about\b", re.I),
    re.compile(r"\bnot\b[^.?!]{0,40}\bbut rather\b", re.I),
    re.compile(r"\bisn['’]t just\b[^.?!]*\bit['’]s\b", re.I),
    re.compile(r"\bnot because\b", re.I),
]


def _find_words(text, words, label, out):
    low = text.lower()
    for w in words:
        if " " in w or "-" in w or "[" in w or "]" in w or "!" in w:
            if w in low:
                out.append((label, w))
        else:
            if re.search(r"\b" + re.escape(w) + r"\b", low):
                out.append((label, w))


def scan(text):
    hits = []
    _find_words(text, AI_LEXICON, "ai-lexicon", hits)
    _find_words(text, AI_PHRASE, "ai-phrase", hits)
    _find_words(text, HYPE, "hype", hits)
    _find_words(text, WEASEL, "weasel-word", hits)
    _find_words(text, THROAT, "throat-clearing", hits)
    _find_words(text, PLATITUDE, "platitude", hits)
    _find_words(text, LLM_LEAK, "llm-leak", hits)
    _find_words(text, COMPLIANCE, "compliance", hits)
    if "—" in text or "—" in text:
        hits.append(("em-dash", "—"))
    for pat in CONTRAST_PATTERNS:
        m = pat.search(text)
        if m:
            hits.append(("contrast-cadence", m.group(0)[:60]))
    return hits


if __name__ == "__main__":
    import sys
    data = sys.stdin.read()
    found = scan(data)
    if not found:
        print("CLEAN")
    else:
        for cat, m in found:
            print(f"{cat}: {m}")
        sys.exit(1)
